//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskComplianceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTable
    {
        public string DAS_ID { get; set; }
        public string NESSIE_ID { get; set; }
        public string Name_Sortable { get; set; }
    }
}
