//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskComplianceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBCP
    {
        public int Sr_No { get; set; }
        public string Vertical { get; set; }
        public string Account { get; set; }
        public string Process { get; set; }
        public string Sub_Process { get; set; }
        public string Activity { get; set; }
        public string Head_Count { get; set; }
        public string Applications_software { get; set; }
        public string Volume { get; set; }
        public string Frequency_daily_weekly_monthly { get; set; }
        public string Any_Volume_trends { get; set; }
        public string SOP_Available { get; set; }
        public string No_of_SOP { get; set; }
        public string Activity_Description { get; set; }
        public string Supplier_who_is_sending { get; set; }
        public string Input_info_needs_to_be_processed { get; set; }
        public string Process_how_it_is_actually_done { get; set; }
        public string Output_what_is_the_output_storage { get; set; }
        public string Customer_end_client_Onshore_Or_biz { get; set; }
        public string SLA_Accuracy_Timelines { get; set; }
        public string SLA_Target { get; set; }
        public string No_Of_errors { get; set; }
        public string Type_of_Errors { get; set; }
        public string Risk_Description { get; set; }
        public string Type_of_Risk_Financial_Non_Financial_Regulatory { get; set; }
        public string Risk_Statement { get; set; }
        public string Likelihood { get; set; }
        public string Impact { get; set; }
        public string Risk_Score { get; set; }
        public string Control_Name { get; set; }
        public string Control_Description { get; set; }
        public string Control_Effectiveness { get; set; }
        public string Design_Effectiveness { get; set; }
        public string Control_Owner { get; set; }
        public string Type_of_control_Preventive_Manual_Detective_Automated_Process_People { get; set; }
        public string Residual_Risk_Considering_Control_Effectiveness { get; set; }
        public string Residual_Risk_Considering_Design_Effectiveness { get; set; }
        public string Test_steps_Methodology { get; set; }
        public string Testing_Objective { get; set; }
        public string What_to_Look_at { get; set; }
        public string What_to_Look_for { get; set; }
        public string What_to_report { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
    }
}
