//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskComplianceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRI
    {
        public int Sr_NO { get; set; }
        public string Vertical { get; set; }
        public string Account { get; set; }
        public string Process { get; set; }
        public string Sub_Process { get; set; }
        public string Activity { get; set; }
        public string Activity_Discription { get; set; }
        public string Risk_Statement { get; set; }
        public string Likelyhood { get; set; }
        public string Impact { get; set; }
        public string Risk_Score { get; set; }
        public string Control_Name { get; set; }
        public string Control_Description { get; set; }
        public string Control_Effectiveness { get; set; }
        public string Design_Effectiveness { get; set; }
        public string Residual_Risk_Considering_Conrol_Effectiveness { get; set; }
        public string Residual_Risk_Considering_Design_Effectiveness { get; set; }
        public string KRI1 { get; set; }
        public string Green { get; set; }
        public string Amber { get; set; }
        public string Red { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
    }
}
