//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskComplianceApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiskAppEntities : DbContext
    {
        public RiskAppEntities()
            : base("name=RiskAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRR> TRRs { get; set; }
        public virtual DbSet<IBCP> IBCPs { get; set; }
        public virtual DbSet<KRI> KRIs { get; set; }
        public virtual DbSet<NTRR> NTRRs { get; set; }
        public virtual DbSet<AdminTable> AdminTables { get; set; }
    }
}
